#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASE_DIR="$ROOT_DIR/dist/releases"
UPDATER_DIR="$RELEASE_DIR/updater"

REMOTE_HOST="${BOOKSTATS_DEPLOY_HOST:-root@carroll-server}"
REMOTE_DIR="${BOOKSTATS_DEPLOY_DIR:-/var/www/kylecarroll/downloads/bookstats}"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

for command_name in node scp ssh; do
  command -v "$command_name" >/dev/null 2>&1 || die "$command_name was not found."
done

[[ -f "$ROOT_DIR/package.json" ]] || die "package.json was not found in $ROOT_DIR"
[[ -d "$RELEASE_DIR" ]] || die "Release directory not found: $RELEASE_DIR"
[[ -d "$UPDATER_DIR" ]] || die "Updater directory not found: $UPDATER_DIR"

VERSION="$(node -p "require('$ROOT_DIR/package.json').version")"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "Unexpected package version: $VERSION"

MAC_ZIP_NAME="BookStats-macOS-v${VERSION}.zip"
WINDOWS_ZIP_NAME="BookStats-Windows-v${VERSION}.zip"

[[ -f "$RELEASE_DIR/$MAC_ZIP_NAME" ]] || die "Missing macOS release: $MAC_ZIP_NAME"
[[ -f "$RELEASE_DIR/$WINDOWS_ZIP_NAME" ]] || die "Missing Windows release: $WINDOWS_ZIP_NAME"

shopt -s nullglob

# Upload only artifacts for the currently configured project version.
RELEASE_ZIPS=("$RELEASE_DIR"/BookStats-*-v"$VERSION".zip)

# Tauri updater payloads/signatures include the release version.
# latest-*.json is regenerated by export.sh and points to those payloads.
UPDATER_FILES=(
  "$UPDATER_DIR"/BookStats-*-v"$VERSION"*
  "$UPDATER_DIR"/latest-*.json
)

shopt -u nullglob

(( ${#RELEASE_ZIPS[@]} > 0 )) || die "No v$VERSION release ZIP files found in $RELEASE_DIR"
(( ${#UPDATER_FILES[@]} > 0 )) || die "No updater files found in $UPDATER_DIR"

REMOTE_STAGE="$REMOTE_DIR/.bookstats-upload-${VERSION}-$$"

cleanup_stage() {
  if [[ -n "${REMOTE_STAGE:-}" ]]; then
    ssh "$REMOTE_HOST" "rm -rf '$REMOTE_STAGE'" >/dev/null 2>&1 || true
  fi
}
trap cleanup_stage EXIT

printf 'BookStats v%s release upload\n' "$VERSION"
printf '  Release ZIPs:  %d\n' "${#RELEASE_ZIPS[@]}"
printf '  Updater files: %d\n' "${#UPDATER_FILES[@]}"
printf '  Destination:   %s:%s/\n\n' "$REMOTE_HOST" "$REMOTE_DIR"

printf 'Preparing remote staging directory...\n'
ssh "$REMOTE_HOST" "mkdir -p '$REMOTE_DIR' && rm -rf '$REMOTE_STAGE' && mkdir -p '$REMOTE_STAGE'"

printf '\nUploading v%s release ZIPs...\n' "$VERSION"
scp "${RELEASE_ZIPS[@]}" "$REMOTE_HOST:$REMOTE_STAGE/"

printf '\nUploading signed updater artifacts and manifests...\n'
scp "${UPDATER_FILES[@]}" "$REMOTE_HOST:$REMOTE_STAGE/"

printf '\nPublishing v%s and removing older BookStats release files...\n' "$VERSION"
ssh "$REMOTE_HOST" "
  set -e

  test -f '$REMOTE_STAGE/$MAC_ZIP_NAME'
  test -f '$REMOTE_STAGE/$WINDOWS_ZIP_NAME'
  test -n \"\$(find '$REMOTE_STAGE' -maxdepth 1 -type f -name 'latest-*.json' -print -quit)\"

  # Remove only BookStats release/updater files. Leave unrelated files alone.
  find '$REMOTE_DIR' -maxdepth 1 -type f \\
    \\( -name 'BookStats-*' -o -name 'latest-*.json' \\) -delete

  # Publish payloads/signatures first, manifests last.
  find '$REMOTE_STAGE' -maxdepth 1 -type f ! -name 'latest-*.json' -exec mv -t '$REMOTE_DIR' -- {} +
  find '$REMOTE_STAGE' -maxdepth 1 -type f -name 'latest-*.json' -exec mv -t '$REMOTE_DIR' -- {} +

  rmdir '$REMOTE_STAGE'

  # Stable manual-download names. Hard links consume no additional file data
  # and are recreated to point at the current version on every release.
  ln -f '$REMOTE_DIR/$MAC_ZIP_NAME' '$REMOTE_DIR/BookStats-macOS.zip'
  ln -f '$REMOTE_DIR/$WINDOWS_ZIP_NAME' '$REMOTE_DIR/BookStats-Windows.zip'

  chmod 644 '$REMOTE_DIR'/*
"

# Publishing succeeded, so the EXIT trap no longer needs to clean staging.
REMOTE_STAGE=""

printf '\nUpload complete.\n'
printf 'Current manual downloads:\n'
printf '  https://kylecarroll.com/downloads/bookstats/BookStats-macOS.zip\n'
printf '  https://kylecarroll.com/downloads/bookstats/BookStats-Windows.zip\n'
printf '\nUpdater manifests:\n'
printf '  https://kylecarroll.com/downloads/bookstats/latest-<platform>.json\n'
printf '\nOnly BookStats v%s release/updater files are retained in the public folder.\n' "$VERSION"
